### ISSUE TITLE
Azure replace VM not working in Canada Central region

### ISSUE THREAD

**Issue by z4ce** [pivotal-cf/cliaas#3]
When trying to replace the VM we get the following error:
```
replace-opsman-vm
2017/05/04 19:48:50 error: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 3603.'."
```
config.yml:
```
azure:
  vhd_image_url: https://opsmanagereastus.blob.core.windows.net/images/ops-manager-1.9.11.vhd
  subscription_id: <redacted>
  client_id: <redacted>
  client_secret: <redacted>
  tenant_id: <redacted>
  resource_group_name: <redacted>
  storage_account_name: <redacted>
  storage_account_key: <redacted>
  storage_container_name: opsmanager
```
